ktor {
    deployment {
        port = 8082
    }
    application {
        modules = [ com.auctor.execution.ApplicationKt.module ]
    }
    database {
        url = "jdbc:postgresql://localhost:5432/execution"
        user = "execution"
        password = "execution"
    }
    redis {
        url = "redis://localhost:6379"
    }
    grpc {
        definition-service-host = "localhost"
        definition-service-port = 9090
    }
    jwt {
        secret = "dev-secret-change-later"
        issuer = "auctor-auth"
        audience = "execution-service"
    }
}
