apiVersion: v1
kind: ConfigMap
metadata:
  name: auctor-config
data:
  ENVIRONMENT: "{{ .Values.environment | default \"dev\" }}"
  LOG_LEVEL: "{{ .Values.logLevel | default \"INFO\" }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: auctor-secrets
type: Opaque
stringData:
  DATABASE_PASSWORD: "{{ .Values.postgresql.auth.password }}"
  REDIS_PASSWORD: "{{ .Values.redis.auth.password | default \"\" }}"
