{{- if .Values.hpa.definition.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "auctor.serviceName" (dict "context" . "name" "definition-service") }}
  labels:
    {{- include "auctor.labels" (dict "context" . "name" "definition-service") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "auctor.serviceName" (dict "context" . "name" "definition-service") }}
  minReplicas: {{ .Values.hpa.definition.minReplicas }}
  maxReplicas: {{ .Values.hpa.definition.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.definition.targetCPUUtilizationPercentage }}
{{- end }}
---
{{- if .Values.hpa.execution.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "auctor.serviceName" (dict "context" . "name" "execution-service") }}
  labels:
    {{- include "auctor.labels" (dict "context" . "name" "execution-service") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "auctor.serviceName" (dict "context" . "name" "execution-service") }}
  minReplicas: {{ .Values.hpa.execution.minReplicas }}
  maxReplicas: {{ .Values.hpa.execution.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.execution.targetCPUUtilizationPercentage }}
{{- end }}
---
{{- if .Values.hpa.web.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "auctor.serviceName" (dict "context" . "name" "web") }}
  labels:
    {{- include "auctor.labels" (dict "context" . "name" "web") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "auctor.serviceName" (dict "context" . "name" "web") }}
  minReplicas: {{ .Values.hpa.web.minReplicas }}
  maxReplicas: {{ .Values.hpa.web.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.web.targetCPUUtilizationPercentage }}
{{- end }}
