{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "auctor.fullname" . }}-ingress
  labels:
    {{- include "auctor.labels" (dict "context" . "name" "ingress") | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "auctor.serviceName" (dict "context" . "name" "web") }}
                port:
                  number: {{ .Values.services.web.httpPort }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "auctor.serviceName" (dict "context" . "name" "definition-service") }}
                port:
                  number: {{ .Values.services.definition.httpPort }}
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: {{ include "auctor.serviceName" (dict "context" . "name" "execution-service") }}
                port:
                  number: {{ .Values.services.execution.httpPort }}
{{- end }}
