apiVersion: v1
kind: Service
metadata:
  name: {{ include "auctor.serviceName" (dict "context" . "name" "definition-service") }}
  labels:
    {{- include "auctor.labels" (dict "context" . "name" "definition-service") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "auctor.selectorLabels" (dict "context" . "name" "definition-service") | nindent 4 }}
  ports:
    - port: {{ .Values.services.definition.httpPort }}
      targetPort: {{ .Values.services.definition.httpPort }}
      name: http
    - port: {{ .Values.services.definition.grpcPort }}
      targetPort: {{ .Values.services.definition.grpcPort }}
      name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auctor.serviceName" (dict "context" . "name" "execution-service") }}
  labels:
    {{- include "auctor.labels" (dict "context" . "name" "execution-service") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "auctor.selectorLabels" (dict "context" . "name" "execution-service") | nindent 4 }}
  ports:
    - port: {{ .Values.services.execution.httpPort }}
      targetPort: {{ .Values.services.execution.httpPort }}
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auctor.serviceName" (dict "context" . "name" "web") }}
  labels:
    {{- include "auctor.labels" (dict "context" . "name" "web") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "auctor.selectorLabels" (dict "context" . "name" "web") | nindent 4 }}
  ports:
    - port: {{ .Values.services.web.httpPort }}
      targetPort: {{ .Values.services.web.httpPort }}
      name: http
