apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: execution-service
  template:
    metadata:
      labels:
        app: execution-service
    spec:
      containers:
        - name: execution
          image: "{{ .Values.image.registry }}/execution-service:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
