replicaCount: 2
environment: sit
logLevel: INFO

ingress:
  host: "auctor-platform.sit.example.com"
  enabled: true

hpa:
  execution:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: "750m"
    memory: "768Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"
