apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auctor
spec:
  project: default
  source:
    repoURL: https://github.com/you/auctor-platform
    path: infra/helm
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: auctor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
