apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: auctor
  namespace: argocd
spec:
  description: Auctor platform
  sourceRepos:
    - https://github.com/kushal-sharma-works/auctor-platform
  destinations:
    - namespace: auctor
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
